image: ruby:2.3.0

before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - ls -al bin
  - chmod +x bin/*
  - ls -al bin
  - ./bin/rake db:migrate RAILS_ENV=test

rspec:
  script:
    - bundle exec rspec
