image: ruby:2.3.0

before_script:
  - sudo apt-get install sqlite3 libsqlite3-dev
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - bundle exec rspec
