AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.0.0
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'db/schema.rb'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Lint/ScriptPermission:
  Exclude:
    - 'bin/*'

Naming/MemoizedInstanceVariableName:
  Enabled: false
