# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e50a2359f2bf466bf6db7aaf5f3a3793aec70e85309f585bb1dced018e50d6e5ff3293fd9ffcd9acdeea2fbaf1be19224c96bffcb81897c53bbe3cf89c35307

test:
  secret_key_base: 52ae43677d4932f4107e6a8d2762b4c581c66a987671fc41401037a2998d6458ab7cc1b3efdc3bd44871dc5f4a0a2c76fde2109464ee307fea474a2bc475bf06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
